name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: ge-proton
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: |
            sudo mv -f makepkg-x86_64.conf /etc/makepkg.conf ;
            makepkg -fsCc --noconfirm ;

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GE-Proton-*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
